# Generated by Django 2.2.6 on 2019-10-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
